FROM golang:1.24-alpine

WORKDIR /app

# Install build dependencies (git, bash, make)
RUN apk add --no-cache git bash make

# Install Air (for live reload)
RUN go install github.com/air-verse/air@latest&& \
    go install github.com/swaggo/swag/cmd/swag@latest
ENV PATH=$PATH:/go/bin

# Copy dependency files
COPY go.mod go.sum ./ 
RUN go mod download
RUN go mod tidy

# Copy the rest of the project
COPY . .

RUN swag init -g cmd/server/main.go -o docs/ --parseDependency --parseInternal

# Default command: run with Air
CMD ["air", "-c", ".air.toml"]
