// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (form_title, form_description, created_by)
VALUES ($1, $2, $3)
RETURNING form_id, form_title, form_description, created_by, form_created_at, form_updated_at, form_status, form_access
`

type CreateFormParams struct {
	FormTitle       string
	FormDescription sql.NullString
	CreatedBy       uuid.NullUUID
}

type CreateFormRow struct {
	FormID          uuid.UUID
	FormTitle       string
	FormDescription sql.NullString
	CreatedBy       uuid.NullUUID
	FormCreatedAt   sql.NullTime
	FormUpdatedAt   sql.NullTime
	FormStatus      NullFormStatus
	FormAccess      NullFormAccess
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (CreateFormRow, error) {
	row := q.db.QueryRowContext(ctx, createForm, arg.FormTitle, arg.FormDescription, arg.CreatedBy)
	var i CreateFormRow
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.CreatedBy,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.FormStatus,
		&i.FormAccess,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :one
DELETE FROM forms
WHERE form_id = $1
RETURNING form_id, form_title, form_description, created_by, form_created_at, form_updated_at, form_status, form_access
`

type DeleteFormRow struct {
	FormID          uuid.UUID
	FormTitle       string
	FormDescription sql.NullString
	CreatedBy       uuid.NullUUID
	FormCreatedAt   sql.NullTime
	FormUpdatedAt   sql.NullTime
	FormStatus      NullFormStatus
	FormAccess      NullFormAccess
}

func (q *Queries) DeleteForm(ctx context.Context, formID uuid.UUID) (DeleteFormRow, error) {
	row := q.db.QueryRowContext(ctx, deleteForm, formID)
	var i DeleteFormRow
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.CreatedBy,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.FormStatus,
		&i.FormAccess,
	)
	return i, err
}

const getFormByID = `-- name: GetFormByID :one
SELECT form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by
FROM forms
WHERE form_id = $1
`

func (q *Queries) GetFormByID(ctx context.Context, formID uuid.UUID) (Form, error) {
	row := q.db.QueryRowContext(ctx, getFormByID, formID)
	var i Form
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.FormStatus,
		&i.FormAccess,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listForms = `-- name: ListForms :many
SELECT form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by
FROM forms
WHERE
    created_by = $1
    AND ($2 IS NULL
         OR form_title ILIKE '%' || $2 || '%'
         OR form_description ILIKE '%' || $2 || '%')
    AND ($3 IS NULL OR form_status = $3)
    AND ($4 IS NULL OR form_access = $4)
ORDER BY
    CASE LOWER(COALESCE($5, 'created'))
        WHEN 'title' THEN form_title
        WHEN 'status' THEN form_status
        WHEN 'access' THEN form_access
        WHEN 'updated' THEN form_updated_at
        ELSE form_created_at
    END
    /* Direction: 'asc' or 'desc' */
    COLLATE "C" 
    /* Note: SQLC currently does not directly allow dynamic ASC/DESC, handle in app code if needed */
LIMIT COALESCE($7, 10)
OFFSET COALESCE($6, 0)
`

type ListFormsParams struct {
	CreatedBy  uuid.NullUUID
	Search     interface{}
	FormStatus interface{}
	FormAccess interface{}
	ShortBy    interface{}
	Offset     interface{}
	Limit      interface{}
}

func (q *Queries) ListForms(ctx context.Context, arg ListFormsParams) ([]Form, error) {
	rows, err := q.db.QueryContext(ctx, listForms,
		arg.CreatedBy,
		arg.Search,
		arg.FormStatus,
		arg.FormAccess,
		arg.ShortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.FormID,
			&i.FormTitle,
			&i.FormDescription,
			&i.FormStatus,
			&i.FormAccess,
			&i.FormCreatedAt,
			&i.FormUpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET
  form_title = COALESCE($1, form_title),
  form_description = COALESCE($2, form_description),
  created_by = COALESCE($3, created_by),
  form_status = COALESCE($4, form_status),
  form_access = COALESCE($5, form_access)
WHERE form_id = $6
RETURNING form_id, form_title, form_description, created_by, form_created_at, form_updated_at, form_status, form_access
`

type UpdateFormParams struct {
	FormTitle       sql.NullString
	FormDescription sql.NullString
	CreatedBy       uuid.NullUUID
	FormStatus      NullFormStatus
	FormAccess      NullFormAccess
	FormID          uuid.UUID
}

type UpdateFormRow struct {
	FormID          uuid.UUID
	FormTitle       string
	FormDescription sql.NullString
	CreatedBy       uuid.NullUUID
	FormCreatedAt   sql.NullTime
	FormUpdatedAt   sql.NullTime
	FormStatus      NullFormStatus
	FormAccess      NullFormAccess
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (UpdateFormRow, error) {
	row := q.db.QueryRowContext(ctx, updateForm,
		arg.FormTitle,
		arg.FormDescription,
		arg.CreatedBy,
		arg.FormStatus,
		arg.FormAccess,
		arg.FormID,
	)
	var i UpdateFormRow
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.CreatedBy,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.FormStatus,
		&i.FormAccess,
	)
	return i, err
}
