// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	UserID           uuid.UUID
	UserFullName     string
	UserEmail        string
	UserGoogleID     string
	UserProfilePicID uuid.NullUUID
	UserCreatedAt    sql.NullTime
	UserUpdatedAt    sql.NullTime
}

type UserImage struct {
	FileID         uuid.UUID
	FileName       string
	FileSize       int64
	FileType       string
	FileUploadedAt sql.NullTime
	UserID         uuid.NullUUID
}
