// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type FormAccess string

const (
	FormAccessPublic     FormAccess = "public"
	FormAccessRestricted FormAccess = "restricted"
)

func (e *FormAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormAccess(s)
	case string:
		*e = FormAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for FormAccess: %T", src)
	}
	return nil
}

type NullFormAccess struct {
	FormAccess FormAccess
	Valid      bool // Valid is true if FormAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormAccess) Scan(value interface{}) error {
	if value == nil {
		ns.FormAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormAccess), nil
}

type FormStatus string

const (
	FormStatusDraft     FormStatus = "draft"
	FormStatusPublished FormStatus = "published"
	FormStatusArchived  FormStatus = "archived"
	FormStatusClosed    FormStatus = "closed"
)

func (e *FormStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormStatus(s)
	case string:
		*e = FormStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FormStatus: %T", src)
	}
	return nil
}

type NullFormStatus struct {
	FormStatus FormStatus
	Valid      bool // Valid is true if FormStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FormStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormStatus), nil
}

type InvitationStatus string

const (
	InvitationStatusOpened    InvitationStatus = "opened"
	InvitationStatusSubmitted InvitationStatus = "submitted"
	InvitationStatusInvited   InvitationStatus = "invited"
	InvitationStatusExpired   InvitationStatus = "expired"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus
	Valid            bool // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type Form struct {
	FormID          uuid.UUID
	FormTitle       string
	FormDescription sql.NullString
	FormStatus      NullFormStatus
	FormAccess      NullFormAccess
	FormCreatedAt   sql.NullTime
	FormUpdatedAt   sql.NullTime
	CreatedBy       uuid.NullUUID
}

type FormField struct {
	FieldID    uuid.UUID
	FieldLabel string
	FieldType  string
	FormID     uuid.UUID
	IsRequired sql.NullBool
	Ordering   int32
}

type FormFieldOption struct {
	OptionID    uuid.UUID
	OptionLabel string
	FieldID     uuid.NullUUID
	Ordering    int32
}

type FormResponse struct {
	ResponseID   uuid.UUID
	FormID       uuid.UUID
	SubmittedAt  sql.NullTime
	RespondentID uuid.NullUUID
	FormOptionID uuid.NullUUID
	FormFieldID  uuid.UUID
	ResponseText sql.NullString
}

type FormResponseFile struct {
	ResponseFileID uuid.UUID
	FileName       string
	FilePath       string
	FileSize       int64
	FileType       string
	FileUploadedAt sql.NullTime
	ResponseID     uuid.UUID
	FormID         uuid.UUID
}

type Invitation struct {
	InvitationID    uuid.UUID
	FormID          uuid.UUID
	InvitedEmail    string
	InvitationToken uuid.NullUUID
	InvitedAt       sql.NullTime
	InvitedBy       uuid.NullUUID
	Status          NullInvitationStatus
	OpenedAt        sql.NullTime
	SubmittedAt     sql.NullTime
}

type User struct {
	UserID           uuid.UUID
	UserFullName     string
	UserEmail        string
	UserGoogleID     string
	UserProfilePicID uuid.NullUUID
	UserCreatedAt    sql.NullTime
	UserUpdatedAt    sql.NullTime
}

type UserImage struct {
	FileID         uuid.UUID
	FileName       string
	FileSize       int64
	FileType       string
	FileUploadedAt sql.NullTime
	UserID         uuid.NullUUID
}
