// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_full_name, user_email, user_google_id, user_profile_pic_id)
VALUES ($1, $2, $3, $4)
RETURNING user_id, user_full_name, user_email, user_google_id, user_profile_pic_id, user_created_at, user_updated_at
`

type CreateUserParams struct {
	UserFullName     string
	UserEmail        string
	UserGoogleID     string
	UserProfilePicID uuid.NullUUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserFullName,
		arg.UserEmail,
		arg.UserGoogleID,
		arg.UserProfilePicID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserGoogleID,
		&i.UserProfilePicID,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_email = $1
`

type GetUserByEmailRow struct {
	UserID             uuid.UUID
	UserFullName       string
	UserEmail          string
	UserProfilePicID   uuid.NullUUID
	UserProfilePicName sql.NullString
	UserCreatedAt      sql.NullTime
	UserUpdatedAt      sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, userEmail)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_google_id = $1
`

type GetUserByGoogleIdRow struct {
	UserID             uuid.UUID
	UserFullName       string
	UserEmail          string
	UserProfilePicID   uuid.NullUUID
	UserProfilePicName sql.NullString
	UserCreatedAt      sql.NullTime
	UserUpdatedAt      sql.NullTime
}

func (q *Queries) GetUserByGoogleId(ctx context.Context, userGoogleID string) (GetUserByGoogleIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleId, userGoogleID)
	var i GetUserByGoogleIdRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_id = $1
`

type GetUserByIDRow struct {
	UserID             uuid.UUID
	UserFullName       string
	UserEmail          string
	UserProfilePicID   uuid.NullUUID
	UserProfilePicName sql.NullString
	UserCreatedAt      sql.NullTime
	UserUpdatedAt      sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}
