FROM golang:alpine

WORKDIR /app

# Install build dependencies (git, bash, make)
RUN apk add --no-cache git bash make

# Install Wgo (for live reload)
RUN go install github.com/bokwoon95/wgo@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest&& \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
ENV PATH=$PATH:/go/bin

# Copy dependency files
COPY go.mod go.sum ./ 
RUN go mod download
RUN go mod tidy

# Copy the rest of the project
COPY . .

RUN swag init -g cmd/server/main.go -o docs/ --parseDependency --parseInternal

# Default command: run with Wgo
CMD ["sh", "-c", "wgo -file=.go -file=.tpl -file=.tmpl -file=.html -file=.env -xfile=_test.go -xdir=assets -xdir=vendor -xdir=internal/db/sqlc go run ./cmd/server"]
