# 1. Base image
FROM node:20-alpine

# 2. Set working directory
WORKDIR /app

# 3. Install pnpm globally
RUN npm install -g pnpm

# 6. Expose port
EXPOSE 3000

# 7. Default command
CMD ["pnpm", "dev"]