import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { TanstackQueryWrapper } from '@/components/wrapper/TanstackQueryWrapper'
import { Toaster } from 'react-hot-toast'
import { GoogleOAuthProvider } from '@react-oauth/google'

import StoreProvider from '@/components/wrapper/StoreProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="1091902491223-a8e9ga2qdf32a9tuqdf32p5j95jus9tt.apps.googleusercontent.com">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Toaster position="top-center" reverseOrder={false} />
          <StoreProvider>
            <TanstackQueryWrapper>{children}</TanstackQueryWrapper>
          </StoreProvider>
        </body>
      </GoogleOAuthProvider>
    </html>
  )
}
