package main

import (
	"log"
	"os"
	// "fmt"

	"github.com/gin-gonic/gin"
	"github.com/giridhar-m-a/custom_form_app/internal/api"

	_ "github.com/giridhar-m-a/custom_form_app/docs" // docs generated by swag
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title My API
// @version 1.0
// @description This is a sample Gin API
// @host localhost:8080
// @BasePath /api/v1
func main() {
	port := os.Getenv("APP_PORT")
	r := gin.Default()

	// Swagger endpoint
	r.GET("/api/docs", func(c *gin.Context) {
		c.Redirect(301, "/api/docs/index.html")
	})
	r.GET("/api/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Register API routes
	api.RegisterRoutes(r)

	if port == "" {
		port = "8080"
	}

	log.Printf("Starting server on port %s...", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}

