package main

import (
	"log"
	"os"

	// "fmt"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/giridhar-m-a/custom_form_app/internal/api"
	"github.com/giridhar-m-a/custom_form_app/internal/db"
	"github.com/giridhar-m-a/custom_form_app/internal/services"

	_ "github.com/giridhar-m-a/custom_form_app/docs" // docs generated by swag
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title My API
// @version 1.0
// @description This is a sample Gin API
// @host localhost:8000
// @schemes http
// @BasePath /api/v1
func main() {
	port := os.Getenv("APP_PORT")
	db.InitDB()
	r := gin.Default()
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:3000", "http://localhost:8000"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
	}))

	// Corrected call to InitMinio
services.InitMinio("192.168.1.10:9000", "giri", "Giri2000", false)

	// Swagger endpoint
	r.GET("/api/docs", func(c *gin.Context) {
		c.Redirect(301, "/api/docs/index.html")
	})
	r.GET("/api/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Register API routes
	api.RegisterRoutes(r)

	if port == "" {
		port = "8080"
	}

	log.Printf("Starting server on port %s...", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}
