basePath: /api/v1
definitions:
  github_com_giridhar-m-a_custom_form_app_internal_dto.CreateFormDTO:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  github_com_giridhar-m-a_custom_form_app_internal_dto.FormResponse:
    properties:
      access:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: m.a.giridhar08@gmail.com
    name: API Support
    url: http://giridhar.dev/
  description: Backend API for Custom Form Application
  title: My API
  version: "1.0"
paths:
  /file-upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file to the specified MinIO bucket and returns file info
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Upload a file to MinIO
      tags:
      - Files
  /forms:
    post:
      consumes:
      - application/json
      description: Creates a new form for the authenticated user
      parameters:
      - description: Form data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/github_com_giridhar-m-a_custom_form_app_internal_dto.CreateFormDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Form created successfully
          schema:
            properties:
              data:
                $ref: '#/definitions/github_com_giridhar-m-a_custom_form_app_internal_dto.FormResponse'
              message:
                type: string
              status:
                type: string
            type: object
        "400":
          description: Invalid request payload
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        "500":
          description: Internal server error
          schema:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new form
      tags:
      - Forms
  /forms/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a form with the specified ID
      parameters:
      - description: Form ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Form retrieved successfully
          schema:
            properties:
              formID:
                type: string
              message:
                type: string
            type: object
        "400":
          description: Bad request
          schema:
            properties:
              message:
                type: string
              status:
                type: integer
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              message:
                type: string
              status:
                type: integer
            type: object
        "500":
          description: Internal server error
          schema:
            properties:
              message:
                type: string
              status:
                type: integer
            type: object
      security:
      - BearerAuth: []
      summary: Get a form by ID
      tags:
      - Forms
  /health:
    get:
      description: Returns OK if the API is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check API health
      tags:
      - health
schemes:
- https
- http
securityDefinitions:
  BearerAuth:
    description: JWT Authorization header using the Bearer scheme.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
