// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getFormSubmissionsByMonth = `-- name: GetFormSubmissionsByMonth :many
SELECT 
    TO_CHAR(submitted_at, 'YYYY-MM') AS month,
    COUNT(*) AS total_submissions
FROM form_submissions
WHERE form_id IN (SELECT form_id FROM forms WHERE created_by = $1)
GROUP BY month
ORDER BY month
`

type GetFormSubmissionsByMonthRow struct {
	Month            string `json:"month"`
	TotalSubmissions int64  `json:"total_submissions"`
}

func (q *Queries) GetFormSubmissionsByMonth(ctx context.Context, createdBy uuid.NullUUID) ([]GetFormSubmissionsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getFormSubmissionsByMonth, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormSubmissionsByMonthRow
	for rows.Next() {
		var i GetFormSubmissionsByMonthRow
		if err := rows.Scan(&i.Month, &i.TotalSubmissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalActiveForms = `-- name: GetTotalActiveForms :one
SELECT COUNT(*) FROM forms WHERE created_by = $1 AND form_status = 'published'
`

func (q *Queries) GetTotalActiveForms(ctx context.Context, createdBy uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalActiveForms, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalClosedForms = `-- name: GetTotalClosedForms :one
SELECT COUNT(*) FROM forms WHERE created_by = $1 AND form_status = 'closed'
`

func (q *Queries) GetTotalClosedForms(ctx context.Context, createdBy uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalClosedForms, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalForms = `-- name: GetTotalForms :one
SELECT COUNT(*) FROM forms WHERE created_by = $1
`

func (q *Queries) GetTotalForms(ctx context.Context, createdBy uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalForms, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalInvitations = `-- name: GetTotalInvitations :one
SELECT COUNT(*) FROM invitations WHERE invited_by = $1
`

func (q *Queries) GetTotalInvitations(ctx context.Context, invitedBy uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalInvitations, invitedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalSubmissions = `-- name: GetTotalSubmissions :one
SELECT COUNT(*) FROM form_submissions WHERE form_id IN (SELECT form_id FROM forms WHERE created_by = $1)
`

func (q *Queries) GetTotalSubmissions(ctx context.Context, createdBy uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSubmissions, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}
