// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createFieldOption = `-- name: CreateFieldOption :one
INSERT INTO form_field_options (field_id, option_label, ordering, is_answer)
VALUES ($1, $2, $3, $4)
RETURNING option_id, field_id, option_label, ordering, is_answer
`

type CreateFieldOptionParams struct {
	FieldID     uuid.NullUUID `json:"field_id"`
	OptionLabel string        `json:"option_label"`
	Ordering    int32         `json:"ordering"`
	IsAnswer    sql.NullBool  `json:"is_answer"`
}

type CreateFieldOptionRow struct {
	OptionID    uuid.UUID     `json:"option_id"`
	FieldID     uuid.NullUUID `json:"field_id"`
	OptionLabel string        `json:"option_label"`
	Ordering    int32         `json:"ordering"`
	IsAnswer    sql.NullBool  `json:"is_answer"`
}

func (q *Queries) CreateFieldOption(ctx context.Context, arg CreateFieldOptionParams) (CreateFieldOptionRow, error) {
	row := q.db.QueryRowContext(ctx, createFieldOption,
		arg.FieldID,
		arg.OptionLabel,
		arg.Ordering,
		arg.IsAnswer,
	)
	var i CreateFieldOptionRow
	err := row.Scan(
		&i.OptionID,
		&i.FieldID,
		&i.OptionLabel,
		&i.Ordering,
		&i.IsAnswer,
	)
	return i, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (
  form_title,
  form_description,
  created_by,
  form_access,
  scheduled_time,
  closing_time,
  is_scheduled,
  invitation_schedule_id,
  invitation_schedule_gap,
  scheduling_id,
  form_status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by, scheduling_id, scheduled_time, closing_time, is_schedule_completed, is_scheduled, invitation_schedule_gap, invitation_schedule_id, is_deleted
`

type CreateFormParams struct {
	FormTitle             string         `json:"form_title"`
	FormDescription       sql.NullString `json:"form_description"`
	CreatedBy             uuid.NullUUID  `json:"created_by"`
	FormAccess            NullFormAccess `json:"form_access"`
	ScheduledTime         sql.NullTime   `json:"scheduled_time"`
	ClosingTime           sql.NullTime   `json:"closing_time"`
	IsScheduled           sql.NullBool   `json:"is_scheduled"`
	InvitationScheduleID  uuid.NullUUID  `json:"invitation_schedule_id"`
	InvitationScheduleGap sql.NullInt32  `json:"invitation_schedule_gap"`
	SchedulingID          uuid.NullUUID  `json:"scheduling_id"`
	FormStatus            NullFormStatus `json:"form_status"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, createForm,
		arg.FormTitle,
		arg.FormDescription,
		arg.CreatedBy,
		arg.FormAccess,
		arg.ScheduledTime,
		arg.ClosingTime,
		arg.IsScheduled,
		arg.InvitationScheduleID,
		arg.InvitationScheduleGap,
		arg.SchedulingID,
		arg.FormStatus,
	)
	var i Form
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.FormStatus,
		&i.FormAccess,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.CreatedBy,
		&i.SchedulingID,
		&i.ScheduledTime,
		&i.ClosingTime,
		&i.IsScheduleCompleted,
		&i.IsScheduled,
		&i.InvitationScheduleGap,
		&i.InvitationScheduleID,
		&i.IsDeleted,
	)
	return i, err
}

const createFormField = `-- name: CreateFormField :one
INSERT INTO form_fields (form_id, field_label, field_type, is_required, ordering)
VALUES ($1, $2, $3, $4, $5)
RETURNING field_id, field_label, field_type, is_required, ordering, form_id
`

type CreateFormFieldParams struct {
	FormID     uuid.UUID         `json:"form_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
}

type CreateFormFieldRow struct {
	FieldID    uuid.UUID         `json:"field_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
	FormID     uuid.UUID         `json:"form_id"`
}

func (q *Queries) CreateFormField(ctx context.Context, arg CreateFormFieldParams) (CreateFormFieldRow, error) {
	row := q.db.QueryRowContext(ctx, createFormField,
		arg.FormID,
		arg.FieldLabel,
		arg.FieldType,
		arg.IsRequired,
		arg.Ordering,
	)
	var i CreateFormFieldRow
	err := row.Scan(
		&i.FieldID,
		&i.FieldLabel,
		&i.FieldType,
		&i.IsRequired,
		&i.Ordering,
		&i.FormID,
	)
	return i, err
}

const deleteFieldOption = `-- name: DeleteFieldOption :one
DELETE FROM form_field_options
WHERE option_id = $1
RETURNING option_id, field_id, option_label, ordering, is_answer
`

type DeleteFieldOptionRow struct {
	OptionID    uuid.UUID     `json:"option_id"`
	FieldID     uuid.NullUUID `json:"field_id"`
	OptionLabel string        `json:"option_label"`
	Ordering    int32         `json:"ordering"`
	IsAnswer    sql.NullBool  `json:"is_answer"`
}

func (q *Queries) DeleteFieldOption(ctx context.Context, optionID uuid.UUID) (DeleteFieldOptionRow, error) {
	row := q.db.QueryRowContext(ctx, deleteFieldOption, optionID)
	var i DeleteFieldOptionRow
	err := row.Scan(
		&i.OptionID,
		&i.FieldID,
		&i.OptionLabel,
		&i.Ordering,
		&i.IsAnswer,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :one
DELETE FROM forms
WHERE form_id = $1
RETURNING form_id, form_title, form_description, created_by, form_created_at, form_updated_at, form_status, form_access
`

type DeleteFormRow struct {
	FormID          uuid.UUID      `json:"form_id"`
	FormTitle       string         `json:"form_title"`
	FormDescription sql.NullString `json:"form_description"`
	CreatedBy       uuid.NullUUID  `json:"created_by"`
	FormCreatedAt   sql.NullTime   `json:"form_created_at"`
	FormUpdatedAt   sql.NullTime   `json:"form_updated_at"`
	FormStatus      NullFormStatus `json:"form_status"`
	FormAccess      NullFormAccess `json:"form_access"`
}

func (q *Queries) DeleteForm(ctx context.Context, formID uuid.UUID) (DeleteFormRow, error) {
	row := q.db.QueryRowContext(ctx, deleteForm, formID)
	var i DeleteFormRow
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.CreatedBy,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.FormStatus,
		&i.FormAccess,
	)
	return i, err
}

const deleteFormField = `-- name: DeleteFormField :one
DELETE FROM form_fields
WHERE field_id = $1
RETURNING field_id, field_label, field_type, is_required, ordering, form_id
`

type DeleteFormFieldRow struct {
	FieldID    uuid.UUID         `json:"field_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
	FormID     uuid.UUID         `json:"form_id"`
}

func (q *Queries) DeleteFormField(ctx context.Context, fieldID uuid.UUID) (DeleteFormFieldRow, error) {
	row := q.db.QueryRowContext(ctx, deleteFormField, fieldID)
	var i DeleteFormFieldRow
	err := row.Scan(
		&i.FieldID,
		&i.FieldLabel,
		&i.FieldType,
		&i.IsRequired,
		&i.Ordering,
		&i.FormID,
	)
	return i, err
}

const getFormByID = `-- name: GetFormByID :one
SELECT form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by, scheduling_id, scheduled_time, closing_time, is_schedule_completed, is_scheduled, invitation_schedule_gap, invitation_schedule_id, is_deleted
FROM forms
WHERE form_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetFormByID(ctx context.Context, formID uuid.UUID) (Form, error) {
	row := q.db.QueryRowContext(ctx, getFormByID, formID)
	var i Form
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.FormStatus,
		&i.FormAccess,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.CreatedBy,
		&i.SchedulingID,
		&i.ScheduledTime,
		&i.ClosingTime,
		&i.IsScheduleCompleted,
		&i.IsScheduled,
		&i.InvitationScheduleGap,
		&i.InvitationScheduleID,
		&i.IsDeleted,
	)
	return i, err
}

const getFormFieldOptionsMap = `-- name: GetFormFieldOptionsMap :one
SELECT COALESCE(
    JSONB_OBJECT_AGG(
        fo.option_id::text,
        JSONB_BUILD_OBJECT(
            'optionId', fo.option_id,
            'optionLabel', fo.option_label,
            'ordering', fo.ordering,
            'fieldId', fo.field_id
        )
    ) FILTER (WHERE fo.option_id IS NOT NULL),
    '{}'::jsonb
) AS "fieldOptionsMap"
FROM form_field_options fo
JOIN form_fields ff ON ff.field_id = fo.field_id
WHERE ff.form_id = $1
`

func (q *Queries) GetFormFieldOptionsMap(ctx context.Context, formID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getFormFieldOptionsMap, formID)
	var fieldOptionsMap interface{}
	err := row.Scan(&fieldOptionsMap)
	return fieldOptionsMap, err
}

const getFormFieldsWithOptions = `-- name: GetFormFieldsWithOptions :many
SELECT
    ff.field_id AS "fieldId",
    ff.field_label AS "fieldLabel",
    ff.field_type AS "fieldType",
    ff.is_required AS "isRequired",
    ff.ordering AS "ordering",
    ff.form_id AS "formId",
    COALESCE(
        JSON_AGG(
            JSONB_BUILD_OBJECT(
                'optionId', fo.option_id,
                'optionLabel', fo.option_label,
                'ordering', fo.ordering,
                'isAnswer', fo.is_answer,
                'fieldId', fo.field_id
            ) ORDER BY fo.ordering
        ) FILTER (WHERE fo.option_id IS NOT NULL),
        '[]'
    )::jsonb AS "options"
FROM form_fields ff
LEFT JOIN form_field_options fo ON ff.field_id = fo.field_id
WHERE ff.form_id = $1
GROUP BY ff.field_id
ORDER BY ff.ordering
`

type GetFormFieldsWithOptionsRow struct {
	FieldId    uuid.UUID         `json:"fieldId"`
	FieldLabel string            `json:"fieldLabel"`
	FieldType  NullFormFieldType `json:"fieldType"`
	IsRequired sql.NullBool      `json:"isRequired"`
	Ordering   int32             `json:"ordering"`
	FormId     uuid.UUID         `json:"formId"`
	Options    json.RawMessage   `json:"options"`
}

func (q *Queries) GetFormFieldsWithOptions(ctx context.Context, formID uuid.UUID) ([]GetFormFieldsWithOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFormFieldsWithOptions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormFieldsWithOptionsRow
	for rows.Next() {
		var i GetFormFieldsWithOptionsRow
		if err := rows.Scan(
			&i.FieldId,
			&i.FieldLabel,
			&i.FieldType,
			&i.IsRequired,
			&i.Ordering,
			&i.FormId,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForms = `-- name: ListForms :many
SELECT
    form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by, scheduling_id, scheduled_time, closing_time, is_schedule_completed, is_scheduled, invitation_schedule_gap, invitation_schedule_id, is_deleted,
    COUNT(*) OVER() as total_count
FROM forms
WHERE
    is_deleted = FALSE
    AND created_by = $1
    AND (
        $2::text IS NULL
        OR form_title ILIKE '%' || $2::text || '%'
        OR form_description ILIKE '%' || $2::text || '%'
    )
    AND ($3::form_status IS NULL OR form_status = $3::form_status)
    AND ($4::form_access IS NULL OR form_access = $4::form_access)
ORDER BY
    CASE
        WHEN COALESCE($5::text, '-updated') = 'updated'
            THEN form_updated_at
    END DESC,
    CASE
        WHEN COALESCE($5::text, '-updated') = '-updated'
            THEN form_updated_at
    END ASC,
    CASE
        WHEN COALESCE($5::text, '-updated') = 'title'
            THEN form_title
    END ASC,
    CASE
        WHEN COALESCE($5::text, '-updated') = '-title'
            THEN form_title
    END DESC
LIMIT COALESCE($7::int, 10)
OFFSET COALESCE($6::int, 0)
`

type ListFormsParams struct {
	CreatedBy  uuid.NullUUID  `json:"created_by"`
	Search     sql.NullString `json:"search"`
	FormStatus NullFormStatus `json:"form_status"`
	FormAccess NullFormAccess `json:"form_access"`
	ShortBy    sql.NullString `json:"short_by"`
	Offset     sql.NullInt32  `json:"offset"`
	Limit      sql.NullInt32  `json:"limit"`
}

type ListFormsRow struct {
	FormID                uuid.UUID      `json:"form_id"`
	FormTitle             string         `json:"form_title"`
	FormDescription       sql.NullString `json:"form_description"`
	FormStatus            NullFormStatus `json:"form_status"`
	FormAccess            NullFormAccess `json:"form_access"`
	FormCreatedAt         sql.NullTime   `json:"form_created_at"`
	FormUpdatedAt         sql.NullTime   `json:"form_updated_at"`
	CreatedBy             uuid.NullUUID  `json:"created_by"`
	SchedulingID          uuid.NullUUID  `json:"scheduling_id"`
	ScheduledTime         sql.NullTime   `json:"scheduled_time"`
	ClosingTime           sql.NullTime   `json:"closing_time"`
	IsScheduleCompleted   sql.NullBool   `json:"is_schedule_completed"`
	IsScheduled           sql.NullBool   `json:"is_scheduled"`
	InvitationScheduleGap sql.NullInt32  `json:"invitation_schedule_gap"`
	InvitationScheduleID  uuid.NullUUID  `json:"invitation_schedule_id"`
	IsDeleted             sql.NullBool   `json:"is_deleted"`
	TotalCount            int64          `json:"total_count"`
}

func (q *Queries) ListForms(ctx context.Context, arg ListFormsParams) ([]ListFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listForms,
		arg.CreatedBy,
		arg.Search,
		arg.FormStatus,
		arg.FormAccess,
		arg.ShortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsRow
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(
			&i.FormID,
			&i.FormTitle,
			&i.FormDescription,
			&i.FormStatus,
			&i.FormAccess,
			&i.FormCreatedAt,
			&i.FormUpdatedAt,
			&i.CreatedBy,
			&i.SchedulingID,
			&i.ScheduledTime,
			&i.ClosingTime,
			&i.IsScheduleCompleted,
			&i.IsScheduled,
			&i.InvitationScheduleGap,
			&i.InvitationScheduleID,
			&i.IsDeleted,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteForm = `-- name: SoftDeleteForm :exec
UPDATE forms
SET is_deleted = TRUE
WHERE form_id = $1
`

func (q *Queries) SoftDeleteForm(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteForm, formID)
	return err
}

const updateFieldOption = `-- name: UpdateFieldOption :one
UPDATE form_field_options
SET
  option_label = COALESCE($2, option_label),
  ordering = COALESCE($3, ordering),
  is_answer = COALESCE($4, is_answer)
WHERE option_id = $1
RETURNING option_id, field_id, option_label, ordering, is_answer
`

type UpdateFieldOptionParams struct {
	OptionID    uuid.UUID    `json:"option_id"`
	OptionLabel string       `json:"option_label"`
	Ordering    int32        `json:"ordering"`
	IsAnswer    sql.NullBool `json:"is_answer"`
}

type UpdateFieldOptionRow struct {
	OptionID    uuid.UUID     `json:"option_id"`
	FieldID     uuid.NullUUID `json:"field_id"`
	OptionLabel string        `json:"option_label"`
	Ordering    int32         `json:"ordering"`
	IsAnswer    sql.NullBool  `json:"is_answer"`
}

func (q *Queries) UpdateFieldOption(ctx context.Context, arg UpdateFieldOptionParams) (UpdateFieldOptionRow, error) {
	row := q.db.QueryRowContext(ctx, updateFieldOption,
		arg.OptionID,
		arg.OptionLabel,
		arg.Ordering,
		arg.IsAnswer,
	)
	var i UpdateFieldOptionRow
	err := row.Scan(
		&i.OptionID,
		&i.FieldID,
		&i.OptionLabel,
		&i.Ordering,
		&i.IsAnswer,
	)
	return i, err
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET
  form_title = COALESCE($1, form_title),
  form_description = COALESCE($2, form_description),
  form_status = COALESCE($3, form_status),
  form_access = COALESCE($4, form_access),
  scheduling_id = COALESCE($5, scheduling_id),
  scheduled_time = COALESCE($6, scheduled_time),
  closing_time = COALESCE($7, closing_time),
  is_schedule_completed = COALESCE($8, is_schedule_completed),
  is_scheduled = COALESCE($9, is_scheduled),
  invitation_schedule_id = COALESCE($10, invitation_schedule_id),
  invitation_schedule_gap = COALESCE($11, invitation_schedule_gap)
WHERE form_id = $12
RETURNING form_id, form_title, form_description, form_status, form_access, form_created_at, form_updated_at, created_by, scheduling_id, scheduled_time, closing_time, is_schedule_completed, is_scheduled, invitation_schedule_gap, invitation_schedule_id, is_deleted
`

type UpdateFormParams struct {
	FormTitle             sql.NullString `json:"form_title"`
	FormDescription       sql.NullString `json:"form_description"`
	FormStatus            NullFormStatus `json:"form_status"`
	FormAccess            NullFormAccess `json:"form_access"`
	SchedulingID          uuid.NullUUID  `json:"scheduling_id"`
	ScheduledTime         sql.NullTime   `json:"scheduled_time"`
	ClosingTime           sql.NullTime   `json:"closing_time"`
	IsScheduleCompleted   sql.NullBool   `json:"is_schedule_completed"`
	IsScheduled           sql.NullBool   `json:"is_scheduled"`
	InvitationScheduleID  uuid.NullUUID  `json:"invitation_schedule_id"`
	InvitationScheduleGap sql.NullInt32  `json:"invitation_schedule_gap"`
	FormID                uuid.UUID      `json:"form_id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRowContext(ctx, updateForm,
		arg.FormTitle,
		arg.FormDescription,
		arg.FormStatus,
		arg.FormAccess,
		arg.SchedulingID,
		arg.ScheduledTime,
		arg.ClosingTime,
		arg.IsScheduleCompleted,
		arg.IsScheduled,
		arg.InvitationScheduleID,
		arg.InvitationScheduleGap,
		arg.FormID,
	)
	var i Form
	err := row.Scan(
		&i.FormID,
		&i.FormTitle,
		&i.FormDescription,
		&i.FormStatus,
		&i.FormAccess,
		&i.FormCreatedAt,
		&i.FormUpdatedAt,
		&i.CreatedBy,
		&i.SchedulingID,
		&i.ScheduledTime,
		&i.ClosingTime,
		&i.IsScheduleCompleted,
		&i.IsScheduled,
		&i.InvitationScheduleGap,
		&i.InvitationScheduleID,
		&i.IsDeleted,
	)
	return i, err
}

const updateFormField = `-- name: UpdateFormField :one
UPDATE form_fields
SET
  field_label = COALESCE($2, field_label),
  field_type = COALESCE($3, field_type),
  is_required = COALESCE($4, is_required),
  ordering = COALESCE($5, ordering)
WHERE field_id = $1
RETURNING field_id, field_label, field_type, is_required, ordering, form_id
`

type UpdateFormFieldParams struct {
	FieldID    uuid.UUID         `json:"field_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
}

type UpdateFormFieldRow struct {
	FieldID    uuid.UUID         `json:"field_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
	FormID     uuid.UUID         `json:"form_id"`
}

func (q *Queries) UpdateFormField(ctx context.Context, arg UpdateFormFieldParams) (UpdateFormFieldRow, error) {
	row := q.db.QueryRowContext(ctx, updateFormField,
		arg.FieldID,
		arg.FieldLabel,
		arg.FieldType,
		arg.IsRequired,
		arg.Ordering,
	)
	var i UpdateFormFieldRow
	err := row.Scan(
		&i.FieldID,
		&i.FieldLabel,
		&i.FieldType,
		&i.IsRequired,
		&i.Ordering,
		&i.FormID,
	)
	return i, err
}
