// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countInvitationsByFormId = `-- name: CountInvitationsByFormId :one
SELECT COUNT(*) AS total_records
FROM invitations
WHERE form_id = $1::uuid
  -- Search filter (Email or Name)
  AND (
        $2::text IS NULL 
        OR invited_name ILIKE '%' || $2::text || '%'
        OR invited_email ILIKE '%' || $2::text || '%'
      )
  -- Status Inclusion filter
  AND (
        $3::invitation_status IS NULL 
        OR status = $3::invitation_status
      )
  -- Status Exclusion filter
  AND (
        $4::invitation_status[] IS NULL 
        OR status <> ALL($4::invitation_status[])
      )
`

type CountInvitationsByFormIdParams struct {
	FormID        uuid.UUID            `json:"form_id"`
	Search        sql.NullString       `json:"search"`
	Status        NullInvitationStatus `json:"status"`
	ExcludeStatus []InvitationStatus   `json:"exclude_status"`
}

func (q *Queries) CountInvitationsByFormId(ctx context.Context, arg CountInvitationsByFormIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvitationsByFormId,
		arg.FormID,
		arg.Search,
		arg.Status,
		pq.Array(arg.ExcludeStatus),
	)
	var total_records int64
	err := row.Scan(&total_records)
	return total_records, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    form_id, 
    invited_email, 
    invited_name, 
    invited_by
)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::uuid
)
ON CONFLICT (invited_email, form_id) 
DO NOTHING
RETURNING invitation_id, invited_email, invited_name
`

type CreateInvitationParams struct {
	FormID    uuid.UUID `json:"form_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	InvitedBy uuid.UUID `json:"invited_by"`
}

type CreateInvitationRow struct {
	InvitationID uuid.UUID `json:"invitation_id"`
	InvitedEmail string    `json:"invited_email"`
	InvitedName  string    `json:"invited_name"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.FormID,
		arg.Email,
		arg.Name,
		arg.InvitedBy,
	)
	var i CreateInvitationRow
	err := row.Scan(&i.InvitationID, &i.InvitedEmail, &i.InvitedName)
	return i, err
}

const createManyInvitations = `-- name: CreateManyInvitations :many
INSERT INTO invitations (
    form_id, 
    invited_email, 
    invited_name, 
    invited_by
)
SELECT
    $1::uuid,
    t1.email,
    t2.name,
    $2::uuid
FROM
    UNNEST($3::text[]) WITH ORDINALITY AS t1(email, idx)
    JOIN UNNEST($4::text[]) WITH ORDINALITY AS t2(name, idx) 
    USING (idx)
ON CONFLICT (invited_email, form_id) 
DO NOTHING
RETURNING invitation_id, invited_email, invited_name
`

type CreateManyInvitationsParams struct {
	FormID    uuid.UUID `json:"form_id"`
	InvitedBy uuid.UUID `json:"invited_by"`
	Emails    []string  `json:"emails"`
	Names     []string  `json:"names"`
}

type CreateManyInvitationsRow struct {
	InvitationID uuid.UUID `json:"invitation_id"`
	InvitedEmail string    `json:"invited_email"`
	InvitedName  string    `json:"invited_name"`
}

func (q *Queries) CreateManyInvitations(ctx context.Context, arg CreateManyInvitationsParams) ([]CreateManyInvitationsRow, error) {
	rows, err := q.db.QueryContext(ctx, createManyInvitations,
		arg.FormID,
		arg.InvitedBy,
		pq.Array(arg.Emails),
		pq.Array(arg.Names),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateManyInvitationsRow
	for rows.Next() {
		var i CreateManyInvitationsRow
		if err := rows.Scan(&i.InvitationID, &i.InvitedEmail, &i.InvitedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations
WHERE invitation_id = $1::uuid
RETURNING invitation_id, invited_email, invited_name, status
`

func (q *Queries) DeleteInvitation(ctx context.Context, invitationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvitation, invitationID)
	return err
}

const getInvitationByFormId = `-- name: GetInvitationByFormId :many
SELECT invitation_id, form_id, invited_email, invited_at, invited_by, status, opened_at, submitted_at, invited_name FROM invitations
WHERE form_id = $1::uuid
  -- Search filter (Email or Name)
  AND (
        $2::text IS NULL 
        OR invited_name ILIKE '%' || $2::text || '%'
        OR invited_email ILIKE '%' || $2::text || '%'
      )
  -- Status Inclusion filter
  AND (
        $3::invitation_status IS NULL 
        OR status = $3::invitation_status
      )
  -- Status Exclusion filter
  AND (
        $4::invitation_status[] IS NULL 
        OR status <> ALL($4::invitation_status[])
      )
ORDER BY invited_at DESC
LIMIT COALESCE($6::int, 10)
OFFSET COALESCE($5::int, 0)
`

type GetInvitationByFormIdParams struct {
	FormID        uuid.UUID            `json:"form_id"`
	Search        sql.NullString       `json:"search"`
	Status        NullInvitationStatus `json:"status"`
	ExcludeStatus []InvitationStatus   `json:"exclude_status"`
	OffsetVal     sql.NullInt32        `json:"offset_val"`
	LimitVal      sql.NullInt32        `json:"limit_val"`
}

func (q *Queries) GetInvitationByFormId(ctx context.Context, arg GetInvitationByFormIdParams) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, getInvitationByFormId,
		arg.FormID,
		arg.Search,
		arg.Status,
		pq.Array(arg.ExcludeStatus),
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.InvitationID,
			&i.FormID,
			&i.InvitedEmail,
			&i.InvitedAt,
			&i.InvitedBy,
			&i.Status,
			&i.OpenedAt,
			&i.SubmittedAt,
			&i.InvitedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE invitations
SET
    status = $1::invitation_status
WHERE
    invitation_id = $2::uuid
RETURNING invitation_id, invited_email, invited_name, status
`

type UpdateInvitationStatusParams struct {
	Status       InvitationStatus `json:"status"`
	InvitationID uuid.UUID        `json:"invitation_id"`
}

type UpdateInvitationStatusRow struct {
	InvitationID uuid.UUID            `json:"invitation_id"`
	InvitedEmail string               `json:"invited_email"`
	InvitedName  string               `json:"invited_name"`
	Status       NullInvitationStatus `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (UpdateInvitationStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateInvitationStatus, arg.Status, arg.InvitationID)
	var i UpdateInvitationStatusRow
	err := row.Scan(
		&i.InvitationID,
		&i.InvitedEmail,
		&i.InvitedName,
		&i.Status,
	)
	return i, err
}
