// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type FormAccess string

const (
	FormAccessPublic     FormAccess = "public"
	FormAccessRestricted FormAccess = "restricted"
)

func (e *FormAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormAccess(s)
	case string:
		*e = FormAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for FormAccess: %T", src)
	}
	return nil
}

type NullFormAccess struct {
	FormAccess FormAccess `json:"form_access"`
	Valid      bool       `json:"valid"` // Valid is true if FormAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormAccess) Scan(value interface{}) error {
	if value == nil {
		ns.FormAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormAccess), nil
}

type FormFieldType string

const (
	FormFieldTypeText        FormFieldType = "text"
	FormFieldTypeNumber      FormFieldType = "number"
	FormFieldTypeDate        FormFieldType = "date"
	FormFieldTypeTime        FormFieldType = "time"
	FormFieldTypeDatetime    FormFieldType = "datetime"
	FormFieldTypeEmail       FormFieldType = "email"
	FormFieldTypePhone       FormFieldType = "phone"
	FormFieldTypeUrl         FormFieldType = "url"
	FormFieldTypeFile        FormFieldType = "file"
	FormFieldTypeImage       FormFieldType = "image"
	FormFieldTypeVideo       FormFieldType = "video"
	FormFieldTypeAudio       FormFieldType = "audio"
	FormFieldTypeCheckbox    FormFieldType = "checkbox"
	FormFieldTypeRadio       FormFieldType = "radio"
	FormFieldTypeDropdown    FormFieldType = "dropdown"
	FormFieldTypeMultiselect FormFieldType = "multiselect"
	FormFieldTypeRating      FormFieldType = "rating"
	FormFieldTypeSlider      FormFieldType = "slider"
	FormFieldTypeColor       FormFieldType = "color"
	FormFieldTypeTextArea    FormFieldType = "textArea"
)

func (e *FormFieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormFieldType(s)
	case string:
		*e = FormFieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FormFieldType: %T", src)
	}
	return nil
}

type NullFormFieldType struct {
	FormFieldType FormFieldType `json:"form_field_type"`
	Valid         bool          `json:"valid"` // Valid is true if FormFieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FormFieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormFieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormFieldType), nil
}

type FormStatus string

const (
	FormStatusDraft     FormStatus = "draft"
	FormStatusPublished FormStatus = "published"
	FormStatusArchived  FormStatus = "archived"
	FormStatusClosed    FormStatus = "closed"
)

func (e *FormStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormStatus(s)
	case string:
		*e = FormStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FormStatus: %T", src)
	}
	return nil
}

type NullFormStatus struct {
	FormStatus FormStatus `json:"form_status"`
	Valid      bool       `json:"valid"` // Valid is true if FormStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FormStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormStatus), nil
}

type InvitationStatus string

const (
	InvitationStatusOpened    InvitationStatus = "opened"
	InvitationStatusSubmitted InvitationStatus = "submitted"
	InvitationStatusInvited   InvitationStatus = "invited"
	InvitationStatusExpired   InvitationStatus = "expired"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type Form struct {
	FormID          uuid.UUID      `json:"form_id"`
	FormTitle       string         `json:"form_title"`
	FormDescription sql.NullString `json:"form_description"`
	FormStatus      NullFormStatus `json:"form_status"`
	FormAccess      NullFormAccess `json:"form_access"`
	FormCreatedAt   sql.NullTime   `json:"form_created_at"`
	FormUpdatedAt   sql.NullTime   `json:"form_updated_at"`
	CreatedBy       uuid.NullUUID  `json:"created_by"`
}

type FormField struct {
	FieldID    uuid.UUID         `json:"field_id"`
	FieldLabel string            `json:"field_label"`
	FieldType  NullFormFieldType `json:"field_type"`
	FormID     uuid.UUID         `json:"form_id"`
	IsRequired sql.NullBool      `json:"is_required"`
	Ordering   int32             `json:"ordering"`
}

type FormFieldOption struct {
	OptionID    uuid.UUID     `json:"option_id"`
	OptionLabel string        `json:"option_label"`
	FieldID     uuid.NullUUID `json:"field_id"`
	Ordering    int32         `json:"ordering"`
	IsAnswer    sql.NullBool  `json:"is_answer"`
}

type FormResponse struct {
	ResponseID   uuid.UUID      `json:"response_id"`
	FormID       uuid.UUID      `json:"form_id"`
	SubmittedAt  sql.NullTime   `json:"submitted_at"`
	RespondentID uuid.NullUUID  `json:"respondent_id"`
	FormFieldID  uuid.UUID      `json:"form_field_id"`
	ResponseText sql.NullString `json:"response_text"`
}

type FormResponseFile struct {
	ResponseFileID uuid.UUID    `json:"response_file_id"`
	FileName       string       `json:"file_name"`
	FilePath       string       `json:"file_path"`
	FileSize       int64        `json:"file_size"`
	FileType       string       `json:"file_type"`
	FileUploadedAt sql.NullTime `json:"file_uploaded_at"`
	ResponseID     uuid.UUID    `json:"response_id"`
	FormID         uuid.UUID    `json:"form_id"`
}

type Invitation struct {
	InvitationID uuid.UUID            `json:"invitation_id"`
	FormID       uuid.UUID            `json:"form_id"`
	InvitedEmail string               `json:"invited_email"`
	InvitedAt    sql.NullTime         `json:"invited_at"`
	InvitedBy    uuid.NullUUID        `json:"invited_by"`
	Status       NullInvitationStatus `json:"status"`
	OpenedAt     sql.NullTime         `json:"opened_at"`
	SubmittedAt  sql.NullTime         `json:"submitted_at"`
	InvitedName  string               `json:"invited_name"`
}

type ResponseOption struct {
	ID           uuid.UUID `json:"id"`
	ResponseID   uuid.UUID `json:"response_id"`
	FormOptionID uuid.UUID `json:"form_option_id"`
}

type User struct {
	UserID           uuid.UUID      `json:"user_id"`
	UserFullName     string         `json:"user_full_name"`
	UserEmail        string         `json:"user_email"`
	UserGoogleID     sql.NullString `json:"user_google_id"`
	UserProfilePicID uuid.NullUUID  `json:"user_profile_pic_id"`
	UserCreatedAt    sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt    sql.NullTime   `json:"user_updated_at"`
	UserPassword     sql.NullString `json:"user_password"`
}

type UserImage struct {
	FileID         uuid.UUID     `json:"file_id"`
	FileName       string        `json:"file_name"`
	FileSize       int64         `json:"file_size"`
	FileType       string        `json:"file_type"`
	FileUploadedAt sql.NullTime  `json:"file_uploaded_at"`
	UserID         uuid.NullUUID `json:"user_id"`
}
