// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: response.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createResponse = `-- name: CreateResponse :one
INSERT INTO form_responses (
    submission_id,
    form_field_id,
    response_text
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text
) RETURNING response_id, submission_id, form_field_id, response_text
`

type CreateResponseParams struct {
	SubmissionID uuid.UUID      `json:"submission_id"`
	FormFieldID  uuid.UUID      `json:"form_field_id"`
	ResponseText sql.NullString `json:"response_text"`
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (FormResponse, error) {
	row := q.db.QueryRowContext(ctx, createResponse, arg.SubmissionID, arg.FormFieldID, arg.ResponseText)
	var i FormResponse
	err := row.Scan(
		&i.ResponseID,
		&i.SubmissionID,
		&i.FormFieldID,
		&i.ResponseText,
	)
	return i, err
}

const createResponseFiles = `-- name: CreateResponseFiles :one
INSERT INTO form_response_files (
    response_id,
    file_name,
    file_path,
    file_size,
    file_type,
    form_id
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::bigint,
    $5::varchar,
    $6::uuid
) RETURNING response_file_id, file_name, file_path, file_size, file_type, file_uploaded_at, response_id, form_id
`

type CreateResponseFilesParams struct {
	ResponseID uuid.UUID `json:"response_id"`
	FileName   string    `json:"file_name"`
	FilePath   string    `json:"file_path"`
	FileSize   int64     `json:"file_size"`
	FileType   string    `json:"file_type"`
	FormID     uuid.UUID `json:"form_id"`
}

func (q *Queries) CreateResponseFiles(ctx context.Context, arg CreateResponseFilesParams) (FormResponseFile, error) {
	row := q.db.QueryRowContext(ctx, createResponseFiles,
		arg.ResponseID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.FileType,
		arg.FormID,
	)
	var i FormResponseFile
	err := row.Scan(
		&i.ResponseFileID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.FileUploadedAt,
		&i.ResponseID,
		&i.FormID,
	)
	return i, err
}

const createResponseOption = `-- name: CreateResponseOption :one
INSERT INTO response_options (
    response_id,
    form_option_id
) VALUES (
    $1::uuid,
    $2::uuid
) RETURNING id, response_id, form_option_id
`

type CreateResponseOptionParams struct {
	ResponseID   uuid.UUID `json:"response_id"`
	FormOptionID uuid.UUID `json:"form_option_id"`
}

func (q *Queries) CreateResponseOption(ctx context.Context, arg CreateResponseOptionParams) (ResponseOption, error) {
	row := q.db.QueryRowContext(ctx, createResponseOption, arg.ResponseID, arg.FormOptionID)
	var i ResponseOption
	err := row.Scan(&i.ID, &i.ResponseID, &i.FormOptionID)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO form_submissions (
    form_id,
    respondent_id
) VALUES (
    $1::uuid,
    $2::uuid
) RETURNING submission_id, form_id, submitted_at, respondent_id
`

type CreateSubmissionParams struct {
	FormID       uuid.UUID     `json:"form_id"`
	RespondentID uuid.NullUUID `json:"respondent_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (FormSubmission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.FormID, arg.RespondentID)
	var i FormSubmission
	err := row.Scan(
		&i.SubmissionID,
		&i.FormID,
		&i.SubmittedAt,
		&i.RespondentID,
	)
	return i, err
}

const getSubmissionById = `-- name: GetSubmissionById :one
SELECT 
    jsonb_build_object(
        'submission_id', fs.submission_id,
        'form_id', fs.form_id,
        'submitted_at', fs.submitted_at,
        'respondent_id', fs.respondent_id,
        'responses', COALESCE(responses.responses, '[]'::jsonb)
    ) AS submission
FROM form_submissions fs
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
        jsonb_build_object(
            'response_id', fr.response_id,
            'form_field_id', fr.form_field_id,
            'response_text', fr.response_text,

            -- options (multi-select)
            'form_field_options', (
                SELECT COALESCE(jsonb_agg(
                    jsonb_build_object(
                        'id', ro.id,
                        'form_option_id', ro.form_option_id
                    )
                ), '[]'::jsonb)
                FROM response_options ro
                WHERE ro.response_id = fr.response_id
            ),

            -- files
            'form_response_files', (
                SELECT COALESCE(jsonb_agg(
                    jsonb_build_object(
                        'response_file_id', frf.response_file_id,
                        'file_name', frf.file_name,
                        'file_path', frf.file_path,
                        'file_size', frf.file_size,
                        'file_type', frf.file_type,
                        'file_uploaded_at', frf.file_uploaded_at
                    )
                ), '[]'::jsonb)
                FROM form_response_files frf
                WHERE frf.response_id = fr.response_id
            )
        )
    ) AS responses
    FROM form_responses fr
    WHERE fr.submission_id = fs.submission_id
) responses ON TRUE
WHERE fs.submission_id = $1
`

func (q *Queries) GetSubmissionById(ctx context.Context, submissionID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionById, submissionID)
	var submission json.RawMessage
	err := row.Scan(&submission)
	return submission, err
}

const getSubmissionCount = `-- name: GetSubmissionCount :one
WITH filtered AS (
    SELECT fs.submission_id
    FROM form_submissions fs
    LEFT JOIN invitations i 
        ON fs.respondent_id = i.invitation_id
    WHERE 
        fs.form_id = $1::uuid
        AND (
            $2::text IS NULL
            OR i.invited_email ILIKE CONCAT('%', $2, '%')
            OR i.invited_name ILIKE CONCAT('%', $2, '%')
        )
)
SELECT COUNT(*) FROM filtered
`

type GetSubmissionCountParams struct {
	FormID uuid.UUID      `json:"form_id"`
	Search sql.NullString `json:"search"`
}

func (q *Queries) GetSubmissionCount(ctx context.Context, arg GetSubmissionCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionCount, arg.FormID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubmissions = `-- name: GetSubmissions :many
WITH filtered AS (
    SELECT 
        fs.submission_id, fs.form_id, fs.submitted_at, fs.respondent_id,
        i.invited_email,
        i.invited_name,
        i.status         AS invitation_status,
        i.invited_at,
        i.opened_at      AS invitation_opened_at
    FROM form_submissions fs
    LEFT JOIN invitations i 
        ON fs.respondent_id = i.invitation_id
    WHERE 
        fs.form_id = $3::uuid
        AND (
            $4::text IS NULL
            OR i.invited_email ILIKE CONCAT('%', $4, '%')
            OR i.invited_name ILIKE CONCAT('%', $4, '%')
        )
)
SELECT submission_id, form_id, submitted_at, respondent_id, invited_email, invited_name, invitation_status, invited_at, invitation_opened_at FROM filtered
ORDER BY submitted_at DESC
LIMIT $2::int
OFFSET $1::int
`

type GetSubmissionsParams struct {
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
	FormID      uuid.UUID      `json:"form_id"`
	Search      sql.NullString `json:"search"`
}

type GetSubmissionsRow struct {
	SubmissionID       uuid.UUID            `json:"submission_id"`
	FormID             uuid.UUID            `json:"form_id"`
	SubmittedAt        sql.NullTime         `json:"submitted_at"`
	RespondentID       uuid.NullUUID        `json:"respondent_id"`
	InvitedEmail       sql.NullString       `json:"invited_email"`
	InvitedName        sql.NullString       `json:"invited_name"`
	InvitationStatus   NullInvitationStatus `json:"invitation_status"`
	InvitedAt          sql.NullTime         `json:"invited_at"`
	InvitationOpenedAt sql.NullTime         `json:"invitation_opened_at"`
}

func (q *Queries) GetSubmissions(ctx context.Context, arg GetSubmissionsParams) ([]GetSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubmissions,
		arg.OffsetCount,
		arg.LimitCount,
		arg.FormID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsRow
	for rows.Next() {
		var i GetSubmissionsRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.FormID,
			&i.SubmittedAt,
			&i.RespondentID,
			&i.InvitedEmail,
			&i.InvitedName,
			&i.InvitationStatus,
			&i.InvitedAt,
			&i.InvitationOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
