// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_full_name, user_email, user_google_id, user_profile_pic_id, user_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, user_full_name, user_email, user_google_id, user_profile_pic_id, user_created_at, user_updated_at
`

type CreateUserParams struct {
	UserFullName     string         `json:"user_full_name"`
	UserEmail        string         `json:"user_email"`
	UserGoogleID     sql.NullString `json:"user_google_id"`
	UserProfilePicID uuid.NullUUID  `json:"user_profile_pic_id"`
	UserPassword     sql.NullString `json:"user_password"`
}

type CreateUserRow struct {
	UserID           uuid.UUID      `json:"user_id"`
	UserFullName     string         `json:"user_full_name"`
	UserEmail        string         `json:"user_email"`
	UserGoogleID     sql.NullString `json:"user_google_id"`
	UserProfilePicID uuid.NullUUID  `json:"user_profile_pic_id"`
	UserCreatedAt    sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt    sql.NullTime   `json:"user_updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserFullName,
		arg.UserEmail,
		arg.UserGoogleID,
		arg.UserProfilePicID,
		arg.UserPassword,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserGoogleID,
		&i.UserProfilePicID,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
RETURNING user_id, user_full_name, user_email, user_profile_pic_id, user_created_at, user_updated_at
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at,
    u.user_password
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_email = $1
`

type GetUserByEmailRow struct {
	UserID             uuid.UUID      `json:"user_id"`
	UserFullName       string         `json:"user_full_name"`
	UserEmail          string         `json:"user_email"`
	UserProfilePicID   uuid.NullUUID  `json:"user_profile_pic_id"`
	UserProfilePicName sql.NullString `json:"user_profile_pic_name"`
	UserCreatedAt      sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt      sql.NullTime   `json:"user_updated_at"`
	UserPassword       sql.NullString `json:"user_password"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, userEmail)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserPassword,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_google_id = $1
`

type GetUserByGoogleIdRow struct {
	UserID             uuid.UUID      `json:"user_id"`
	UserFullName       string         `json:"user_full_name"`
	UserEmail          string         `json:"user_email"`
	UserProfilePicID   uuid.NullUUID  `json:"user_profile_pic_id"`
	UserProfilePicName sql.NullString `json:"user_profile_pic_name"`
	UserCreatedAt      sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt      sql.NullTime   `json:"user_updated_at"`
}

func (q *Queries) GetUserByGoogleId(ctx context.Context, userGoogleID sql.NullString) (GetUserByGoogleIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleId, userGoogleID)
	var i GetUserByGoogleIdRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.user_id, 
    u.user_full_name, 
    u.user_email, 
    u.user_profile_pic_id, 
    i.file_name AS user_profile_pic_name,
    u.user_created_at, 
    u.user_updated_at
FROM users u
LEFT JOIN user_images i
    ON u.user_profile_pic_id = i.file_id
WHERE u.user_id = $1
`

type GetUserByIDRow struct {
	UserID             uuid.UUID      `json:"user_id"`
	UserFullName       string         `json:"user_full_name"`
	UserEmail          string         `json:"user_email"`
	UserProfilePicID   uuid.NullUUID  `json:"user_profile_pic_id"`
	UserProfilePicName sql.NullString `json:"user_profile_pic_name"`
	UserCreatedAt      sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt      sql.NullTime   `json:"user_updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserProfilePicName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  user_full_name = COALESCE($1, user_full_name),
  user_email = COALESCE($2, user_email),
  user_profile_pic_id = COALESCE($3, user_profile_pic_id),
  user_password = COALESCE($4, user_password),  
  user_google_id = COALESCE($5, user_google_id)
WHERE user_id = $6
RETURNING user_id, user_full_name, user_email, user_profile_pic_id, user_created_at, user_updated_at
`

type UpdateUserParams struct {
	UserFullName     sql.NullString `json:"user_full_name"`
	UserEmail        sql.NullString `json:"user_email"`
	UserProfilePicID uuid.NullUUID  `json:"user_profile_pic_id"`
	UserPassword     sql.NullString `json:"user_password"`
	UserGoogleID     sql.NullString `json:"user_google_id"`
	UserID           uuid.UUID      `json:"user_id"`
}

type UpdateUserRow struct {
	UserID           uuid.UUID     `json:"user_id"`
	UserFullName     string        `json:"user_full_name"`
	UserEmail        string        `json:"user_email"`
	UserProfilePicID uuid.NullUUID `json:"user_profile_pic_id"`
	UserCreatedAt    sql.NullTime  `json:"user_created_at"`
	UserUpdatedAt    sql.NullTime  `json:"user_updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.UserFullName,
		arg.UserEmail,
		arg.UserProfilePicID,
		arg.UserPassword,
		arg.UserGoogleID,
		arg.UserID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserFullName,
		&i.UserEmail,
		&i.UserProfilePicID,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}
