// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profile_pics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUserProfilePic = `-- name: CreateUserProfilePic :one
INSERT INTO user_images (file_name, file_size, file_type, user_id)
VALUES ($1, $2, $3, $4)
RETURNING file_id, file_name, file_size, file_type, file_uploaded_at, user_id
`

type CreateUserProfilePicParams struct {
	FileName string        `json:"file_name"`
	FileSize int64         `json:"file_size"`
	FileType string        `json:"file_type"`
	UserID   uuid.NullUUID `json:"user_id"`
}

func (q *Queries) CreateUserProfilePic(ctx context.Context, arg CreateUserProfilePicParams) (UserImage, error) {
	row := q.db.QueryRowContext(ctx, createUserProfilePic,
		arg.FileName,
		arg.FileSize,
		arg.FileType,
		arg.UserID,
	)
	var i UserImage
	err := row.Scan(
		&i.FileID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.FileUploadedAt,
		&i.UserID,
	)
	return i, err
}
